<?php 

if(isset($_POST['url'])){
	$url = $_POST['url'];
}else{
	echo 'Go back and input URL';
	exit;
}

	

 ?>


<?php 

$list = array
(
"Category;/;Asin;/;Price",

);


 ?>
<?php 

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
$headers[] = 'Accept-Language: en-US,en;q=0.5';
$headers[] = 'Proxy-Authorization: Basic Lmh4QDE3MTUzODY7YmQuOmUxZmtZY3FLOUNRTm0yQ3VOUnV6SDU2RTF2MGxOQllnS3IxeDkwL3N0c0U9';
$headers[] = 'Connection: keep-alive';
$headers[] = 'Cookie: session-id=261-1084993-7560262; session-id-time=2082787201l; i18n-prefs=INR; csm-hit=tb:P90WXW9N9VYGMWR0TFKN+s-P90WXW9N9VYGMWR0TFKN|1552756598167&t:1552756598167&adb:adblk_no; ubid-acbin=257-3967806-9511430; x-wl-uid=1Zsty0Y4QqdjJkkr/ADheTH39m/WHo0VyFiu2eqDjcSOGs7/+2NnTPcFy0mYj04l8Xs13KAOzYUQ=; session-token=dTUV6RCuS1mTgNggA9b2iukCAJT1h5EtOIP8NBEzbR2C7lQ5h/2GkdYpt3a3AUDu7Fu9dvCEd0tNKxkEpojR7ZsDWLKQ5eObP652uZmFIpDX1VmoqPF6o0cBTnjFrLK3tSjXfbr2ww5Xe/JLRX0m3k1P6bcuRTdggVFgMIAIBC5DdHfOX3cf1UcoPN+a7yEp; lc-acbin=en_IN';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Te: Trailers';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$html = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);



$doc = new DOMDocument();

@$doc->loadHTML($html);

$finder = new DomXPath($doc);

$divs = $finder->query("//*[contains(@class, 'a-link-normal')]");

$the_urls = array();



$flag = 0;
foreach ($divs as  $div) {

	if($flag>=1){
		array_push($the_urls, 'https://www.amazon.in'.$div->getAttribute('href'));
		//array_push($the_urls_keys, $div->getAttribute('title'));
	}
	$flag++;
	
	
	
}


//$the_urls=array_combine($the_urls_keys,$the_urls);
// echo "<pre>";
// print_r($the_urls);
// exit;

$total_number_of_urls = count($the_urls);


$count = 0;

foreach ($the_urls as $key => $the_url) {
	sleep(4);

	echo '<hr>';
	echo $the_url;
	echo '<hr>';


	$count++;


for ($i=1; $i <200 ; $i++) {


	
	$pagination = '&page='.$i.'&ie=UTF8';



$my_url = str_replace("&ie=UTF8",$pagination,$the_url);


$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $my_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
$headers[] = 'Accept-Language: en-US,en;q=0.5';
$headers[] = 'Proxy-Authorization: Basic Lmh4QDE3MTUzODY7YmQuOmUxZmtZY3FLOUNRTm0yQ3VOUnV6SDU2RTF2MGxOQllnS3IxeDkwL3N0c0U9';
$headers[] = 'Connection: keep-alive';
$headers[] = 'Cookie: session-id=261-1084993-7560262; session-id-time=2082787201l; i18n-prefs=INR; csm-hit=tb:P90WXW9N9VYGMWR0TFKN+s-P90WXW9N9VYGMWR0TFKN|1552756598167&t:1552756598167&adb:adblk_no; ubid-acbin=257-3967806-9511430; x-wl-uid=1Zsty0Y4QqdjJkkr/ADheTH39m/WHo0VyFiu2eqDjcSOGs7/+2NnTPcFy0mYj04l8Xs13KAOzYUQ=; session-token=dTUV6RCuS1mTgNggA9b2iukCAJT1h5EtOIP8NBEzbR2C7lQ5h/2GkdYpt3a3AUDu7Fu9dvCEd0tNKxkEpojR7ZsDWLKQ5eObP652uZmFIpDX1VmoqPF6o0cBTnjFrLK3tSjXfbr2ww5Xe/JLRX0m3k1P6bcuRTdggVFgMIAIBC5DdHfOX3cf1UcoPN+a7yEp; lc-acbin=en_IN';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Te: Trailers';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$html = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);



$doc = new DOMDocument();

@$doc->loadHTML($html);

$finder = new DomXPath($doc);

$divs = $finder->query("//*[contains(@class, 's-item-container')]");

if($divs->length){


foreach ($divs as  $div) {

	sleep(3);

$data = $div->getElementsByTagName('a');

if($data->length){
	$href = $data[2]->getAttribute('href');

	$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $href);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
$headers[] = 'Accept-Language: en-US,en;q=0.5';
$headers[] = 'Proxy-Authorization: Basic Lmh4QDE3MTUzODY7YmQuOmUxZmtZY3FLOUNRTm0yQ3VOUnV6SDU2RTF2MGxOQllnS3IxeDkwL3N0c0U9';
$headers[] = 'Connection: keep-alive';
$headers[] = 'Cookie: session-id=261-1084993-7560262; session-id-time=2082787201l; i18n-prefs=INR; csm-hit=tb:P90WXW9N9VYGMWR0TFKN+s-P90WXW9N9VYGMWR0TFKN|1552756598167&t:1552756598167&adb:adblk_no; ubid-acbin=257-3967806-9511430; x-wl-uid=1Zsty0Y4QqdjJkkr/ADheTH39m/WHo0VyFiu2eqDjcSOGs7/+2NnTPcFy0mYj04l8Xs13KAOzYUQ=; session-token=dTUV6RCuS1mTgNggA9b2iukCAJT1h5EtOIP8NBEzbR2C7lQ5h/2GkdYpt3a3AUDu7Fu9dvCEd0tNKxkEpojR7ZsDWLKQ5eObP652uZmFIpDX1VmoqPF6o0cBTnjFrLK3tSjXfbr2ww5Xe/JLRX0m3k1P6bcuRTdggVFgMIAIBC5DdHfOX3cf1UcoPN+a7yEp; lc-acbin=en_IN';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Te: Trailers';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$html = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$doc = new DOMDocument();
@$doc->loadHTML($html);
$new_divs = $doc->getElementById( 'wayfinding-breadcrumbs_feature_div' );
// print_r($new_divs->nodeValue);
// exit;

	$href = explode("/",$href);

	

	// echo "<pre>";
	// print_r($array = iterator_to_array($data));

	if(isset($href[5])){

		$asin = trim($href[5]);
	
	if($data->length==8){
		$price = preg_replace('/^\p{Z}+|\p{Z}+$/u', '', $data[2]->nodeValue);
	}else if($data->length==10){
		$price = preg_replace('/^\p{Z}+|\p{Z}+$/u', '', $data[4]->nodeValue);
	}else if($data->length==9){
		$price = preg_replace('/^\p{Z}+|\p{Z}+$/u', '', $data[4]->nodeValue);
	}else if($data->length==5 || $data->length==6 || $data->length==7){
		$price = preg_replace('/^\p{Z}+|\p{Z}+$/u', '', $data[2]->nodeValue);
	}else{
		$price = 'could_not_be_scrapped';
	}

	
	if(is_array ($price)){
		$price = $price[0];
	}else{
		$price = explode("(",$price);
		$price = $price[0];
	}
	
	$price = preg_replace('/[^0-9.-]+/', '', $price);
	//$key = html_entity_decode($key, ENT_QUOTES, 'utf-8');

	if(isset($new_divs)){
		$node_val = html_entity_decode($new_divs->nodeValue, ENT_QUOTES, 'utf-8');
		$node_val = str_replace('›', '>', $node_val);
		$node_val = trim($node_val);
		//below code is special kind of trim
		$node_val = preg_replace('/^\p{Z}+|\p{Z}+$/u', '', $node_val);
		$vals = $node_val.";/;".$asin.";/;".$price;
	}else{
		$vals = ''.";/;".$asin.";/;".$price;
	}
	


     array_push($list,$vals );

     $cnt = $count.' -> '.$asin;

     echo "<script>console.log(".json_encode($cnt).")</script>";
	echo $count.' running of '.$total_number_of_urls.' urls '.$asin.' scrapped';
	echo "<br>";
	ob_flush();
    flush();
   sleep(3);

	
	// echo $key.' -> '.$asin.' -> '.$price.'<br>';
	// echo '<hr>';
		
	}
	
	
	
}



}

// echo $my_url;
// echo '<hr>';echo '<hr>';echo '<hr>';
}else{
	break;
}


}





}


$file_name = $total_number_of_urls.'.csv';


$file = fopen($file_name,"w");

foreach ($list as $line)
  {
  fputcsv($file,explode(';/;',$line));
  }

fclose($file);


 ?>
<a href="<?php echo $file_name; ?>">Download The Product List</a>

